version: "3.9"
services:
  web:
    build: .
    command: yarn dev
    ports:
      - "3000:3000" # For the 'web' app
      - "3001:3001" # For the 'docs' app
      - "8000:8000" # For the 'server' app
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - .:/app
      # Protect all node_modules folders from the volume mount
      - /app/node_modules
      - /app/apps/docs/node_modules
      - /app/apps/server/node_modules
      - /app/apps/web/node_modules
      - /app/packages/eslint-config/node_modules
      - /app/packages/ui/node_modules
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]